//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_8.MyTempConvertServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyTempConvertServiceReference.TempConvertServiceSoap")]
    public interface TempConvertServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Lab_8.MyTempConvertServiceReference.HelloWorldResponse HelloWorld(Lab_8.MyTempConvertServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.HelloWorldResponse> HelloWorldAsync(Lab_8.MyTempConvertServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем value из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponse FahrenheitToCelsius(Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем value из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponse CelsiusToFahrenheit(Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Lab_8.MyTempConvertServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab_8.MyTempConvertServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab_8.MyTempConvertServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab_8.MyTempConvertServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FahrenheitToCelsiusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FahrenheitToCelsius", Namespace="http://tempuri.org/", Order=0)]
        public Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequestBody Body;
        
        public FahrenheitToCelsiusRequest() {
        }
        
        public FahrenheitToCelsiusRequest(Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FahrenheitToCelsiusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public FahrenheitToCelsiusRequestBody() {
        }
        
        public FahrenheitToCelsiusRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FahrenheitToCelsiusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FahrenheitToCelsiusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponseBody Body;
        
        public FahrenheitToCelsiusResponse() {
        }
        
        public FahrenheitToCelsiusResponse(Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FahrenheitToCelsiusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FahrenheitToCelsiusResult;
        
        public FahrenheitToCelsiusResponseBody() {
        }
        
        public FahrenheitToCelsiusResponseBody(string FahrenheitToCelsiusResult) {
            this.FahrenheitToCelsiusResult = FahrenheitToCelsiusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CelsiusToFahrenheitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CelsiusToFahrenheit", Namespace="http://tempuri.org/", Order=0)]
        public Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequestBody Body;
        
        public CelsiusToFahrenheitRequest() {
        }
        
        public CelsiusToFahrenheitRequest(Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CelsiusToFahrenheitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public CelsiusToFahrenheitRequestBody() {
        }
        
        public CelsiusToFahrenheitRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CelsiusToFahrenheitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CelsiusToFahrenheitResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponseBody Body;
        
        public CelsiusToFahrenheitResponse() {
        }
        
        public CelsiusToFahrenheitResponse(Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CelsiusToFahrenheitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelsiusToFahrenheitResult;
        
        public CelsiusToFahrenheitResponseBody() {
        }
        
        public CelsiusToFahrenheitResponseBody(string CelsiusToFahrenheitResult) {
            this.CelsiusToFahrenheitResult = CelsiusToFahrenheitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempConvertServiceSoapChannel : Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempConvertServiceSoapClient : System.ServiceModel.ClientBase<Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap>, Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap {
        
        public TempConvertServiceSoapClient() {
        }
        
        public TempConvertServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempConvertServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempConvertServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempConvertServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab_8.MyTempConvertServiceReference.HelloWorldResponse Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap.HelloWorld(Lab_8.MyTempConvertServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab_8.MyTempConvertServiceReference.HelloWorldRequest inValue = new Lab_8.MyTempConvertServiceReference.HelloWorldRequest();
            inValue.Body = new Lab_8.MyTempConvertServiceReference.HelloWorldRequestBody();
            Lab_8.MyTempConvertServiceReference.HelloWorldResponse retVal = ((Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.HelloWorldResponse> Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap.HelloWorldAsync(Lab_8.MyTempConvertServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Lab_8.MyTempConvertServiceReference.HelloWorldRequest inValue = new Lab_8.MyTempConvertServiceReference.HelloWorldRequest();
            inValue.Body = new Lab_8.MyTempConvertServiceReference.HelloWorldRequestBody();
            return ((Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponse Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap.FahrenheitToCelsius(Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest request) {
            return base.Channel.FahrenheitToCelsius(request);
        }
        
        public string FahrenheitToCelsius(string value) {
            Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest inValue = new Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest();
            inValue.Body = new Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequestBody();
            inValue.Body.value = value;
            Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponse retVal = ((Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap)(this)).FahrenheitToCelsius(inValue);
            return retVal.Body.FahrenheitToCelsiusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponse> Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap.FahrenheitToCelsiusAsync(Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest request) {
            return base.Channel.FahrenheitToCelsiusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(string value) {
            Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest inValue = new Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequest();
            inValue.Body = new Lab_8.MyTempConvertServiceReference.FahrenheitToCelsiusRequestBody();
            inValue.Body.value = value;
            return ((Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap)(this)).FahrenheitToCelsiusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponse Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap.CelsiusToFahrenheit(Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest request) {
            return base.Channel.CelsiusToFahrenheit(request);
        }
        
        public string CelsiusToFahrenheit(string value) {
            Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest inValue = new Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest();
            inValue.Body = new Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequestBody();
            inValue.Body.value = value;
            Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponse retVal = ((Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap)(this)).CelsiusToFahrenheit(inValue);
            return retVal.Body.CelsiusToFahrenheitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponse> Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap.CelsiusToFahrenheitAsync(Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest request) {
            return base.Channel.CelsiusToFahrenheitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(string value) {
            Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest inValue = new Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequest();
            inValue.Body = new Lab_8.MyTempConvertServiceReference.CelsiusToFahrenheitRequestBody();
            inValue.Body.value = value;
            return ((Lab_8.MyTempConvertServiceReference.TempConvertServiceSoap)(this)).CelsiusToFahrenheitAsync(inValue);
        }
    }
}
